version: '3.9'

services:
  application:
    restart: always
    container_name: employees-backend
    hostname: employees-backend
    # Переменные окружения на проде лучше задать
    # на самом сервере, либо в k8s, если он у нас есть.
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - TEST_MONGODB_URL=mongodb://mongodb:27017/test_db
      - DEBUG=True
      - MODE=Dev
    build:
      context: .
    command:
      python3 -m src
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    container_name: employees-mongo
    hostname: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./db_data:/data/db
      - .:/home
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    name: employees-network
    driver: bridge